apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklineapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklineapp
  template:
    metadata:
      labels:
        app: tasklineapp
    spec:
      containers:
        - name: tasklineapp
          image: ghcr.io/eunice-osuagwuh/tasklineapp:b04f4970bddbfed9f86c8e9b1c5c37819c741631
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret